version: 2

version: 2
sphinx:
  # Path to your Sphinx configuration file. -> https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
  builder: html
  configuration: source/conf.py
  fail_on_warning: true


python:
  install:
    - requirements: source/rtd_requirements.txt
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3"
